### ISSUE TITLE
Resist Corporation

### ISSUE THREAD

**Issue by aaravdave** [kethan1/kethan1#1]
Resist is a Corporation founded by Aarav Dave currently consisting of three members. This issue is about your status in Resist if you decide to join.

You will be a:
Tester (Giving Feedback)
Coder (Coding The Arduino)

Thank you for your time.
- Aarav Dave, Resist Member

Approved by Resist Corporation, 3/3 members pass
OFFICIAL [RESIST](https://github.com/Resist-Tech)

**Comment by kethan1** [comment]
Thank you for the invitation! I really like that Resist-Tech seems to be. I accept the invitation. Again, thank you!

**Comment by aaravdave** [comment]
Yes, thanks!
